version: '3.8'

services:

  server:
    image: ghcr.io/silkkycloud/searxng:latest
    hostname: searx
    networks:
      - backend
      - proxy_net
    deploy:
      mode: replicated
      replicas: 6
      placement:
        max_replicas_per_node: 2
        constraints:
          - "node.labels.web_server == true"
      update_config:
        failure_action: rollback
      resources:
        limits:
          cpus: '4'
          memory: 8GB
        reservations:
          cpus: '0.2'
          memory: 1G
    environment:
      - HOSTNAME=${HOSTNAME}
      - SECRET_KEY=${SECRET_KEY}
      - MORTY_KEY=${MORTY_KEY}

  filtron:

  morty:

  redis:
    image: redis:6.2.6-alpine
    hostname: redis
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.web_server == true"
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 50M

networks:
  public:
    external: true
  proxy_net:
    external: true

  backend:
    driver: overlay
    internal: true
    driver_opts:
      encrypted: "true"
      com.docker.network.driver.mtu: 1450