use_default_settings: true

general:
  debug: false
  instance_name: "SearX Silkky.Cloud"
  contact_url: "https://www.silkky.cloud/contact"
  enable_metrics: false

brand:
  new_issue_url: https://github.com/searxng/searxng/issues/new
  docs_url: https://docs.searxng.org/
  public_instances: https://searx.space
  wiki_url: https://github.com/searxng/searxng/wiki
  issue_url: https://github.com/searxng/searxng/issues

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  default_lang: ""
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html

server:
  port: 8080
  bind_address: "0.0.0.0"
  base_url: "https://ENV_HOSTNAME/"
  limiter: true
  secret_key: "ENV_SECRET_KEY"
  image_proxy: true
  http_protocol_version: "1.0"
  method: "GET"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

redis:
  url: redis://redis:6379/0

ui:
  static_path: ""
  templates_path: ""
  query_in_title: false
  default_theme: simple
  default_locale: ""
  theme_args:
    oscar_style: logicodev
    simple_style: dark

outgoing:
  request_timeout: 4.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true
  proxies:
    all://:
      - http://tinyproxy:8080